### ISSUE TITLE
ModuleNotFoundError: No module named 'botocore.vendored'

### ISSUE THREAD

**Issue by sreevishal** [phanein/deepwalk#100]
I followed the installation steps from readme. It showed it installed successfully. However i am not able to run deepwalk. 

Below is the full error message:
c:\deepwalk-master>deepwalk
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\deepwalk-script.py", line 11, in <module>
    load_entry_point('deepwalk==1.0.3', 'console_scripts', 'deepwalk')()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\deepwalk-1.0.3-py3.7.egg\deepwalk\__main__.py", line 15, in <module>
    from gensim.models import Word2Vec
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\gensim-3.8.0-py3.7-win-amd64.egg\gensim\__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\gensim-3.8.0-py3.7-win-amd64.egg\gensim\parsing\__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\gensim-3.8.0-py3.7-win-amd64.egg\gensim\parsing\preprocessing.py", line 42, in <module>
    from gensim import utils
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\gensim-3.8.0-py3.7-win-amd64.egg\gensim\utils.py", line 45, in <module>
    from smart_open import open
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\smart_open-1.8.4-py3.7.egg\smart_open\__init__.py", line 28, in <module>
    from .smart_open_lib import open, smart_open, register_compressor
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\smart_open-1.8.4-py3.7.egg\smart_open\smart_open_lib.py", line 40, in <module>
    import boto3
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\boto3-1.9.212-py3.7.egg\boto3\__init__.py", line 16, in <module>
    from boto3.session import Session
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\boto3-1.9.212-py3.7.egg\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\botocore\session.py", line 29, in <module>
    import botocore.configloader
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\botocore\configloader.py", line 19, in <module>
    from botocore.compat import six
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\botocore\compat.py", line 24, in <module>
    from botocore.vendored import six
ModuleNotFoundError: No module named 'botocore.vendored'

Can you help?

**Comment by GTmac** [comment]
Searched for this error message and it seems to be AWS related: https://github.com/aws/aws-cli/issues/3092

I guess you are running DeepWalk on an AWS machine? Looks like the problem is not with DeepWalk.

**Comment by sreevishal** [comment]
Its not AWS and its just my windows machine. without proxy set or not behind any firewall.
