### ISSUE TITLE
RuntimeError: dictionary changed size during iteration 

### ISSUE THREAD

**Issue by Carlyen** [phanein/deepwalk#121]
Hello, 
I'm using windows.
I am trying to run Deepwalk on Pycharm with the examples provided. When I test Karate.adjlist, it works perfectly, but when I try to run it with p2p-Gnutella08.edgelist or any other .adjlist file (no matter the size), it gives me the following error,

Traceback (most recent call last):
  File "C:\Python\Python385\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python385\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Caro\PycharmProjects\HelloWorld\venv\Scripts\deepwalk.exe\__main__.py", line 7, in <module>
  File "c:\users\Caro\pycharmprojects\helloworld\venv\lib\site-packages\deepwalk\__main__.py", line 162, in main
    process(args)
  File "c:\users\Caro\pycharmprojects\helloworld\venv\lib\site-packages\deepwalk\__main__.py", line 52, in process
    G = graph.load_adjacencylist(args.input, undirected=args.undirected)
  File "c:\users\Caro\pycharmprojects\helloworld\venv\lib\site-packages\deepwalk\graph.py", line 240, in load_adjacencylist
    G = G.make_undirected()
  File "c:\users\Caro\pycharmprojects\helloworld\venv\lib\site-packages\deepwalk\graph.py", line 59, in make_undirected
    for v in self.keys():
RuntimeError: dictionary changed size during iteration

  Thank you for the help.

**Comment by flyking1994** [comment]
set the format to edgelist
