### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by loretoparisi** [phanein/deepwalk#13]
I had this exception:

``` shell
macbookproloreto:deepwalk admin$ deepwalk --input example_graphs/karate.adjlist --output karate.embeddings
Number of nodes: 34
Number of walks: 340
Data size (walks*length): 13600
Walking...
Training...
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 9, in <module>
    load_entry_point('deepwalk==1.0.1', 'console_scripts', 'deepwalk')()
  File "/Library/Python/2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/__main__.py", line 157, in main
    process(args)
  File "/Library/Python/2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/__main__.py", line 71, in process
    model = Word2Vec(walks, size=args.representation_size, window=args.window_size, min_count=0, workers=args.workers)
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 444, in __init__
    self.build_vocab(sentences, trim_rule=trim_rule)
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 510, in build_vocab
    self.finalize_vocab()  # build tables & arrays
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 640, in finalize_vocab
    self.reset_weights()
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 986, in reset_weights
    self.syn0[i] = self.seeded_vector(self.index2word[i] + str(self.seed))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
macbookproloreto:deepwalk admin$ vi /Library/Python/2.7/site-packages/gensim/models/word2vec.py
```

I have fixed it just removing `str()` from the line `986`:

``` python
for i in xrange(len(self.vocab)):
            # construct deterministic seed from word AND seed argument
            self.syn0[i] = self.seeded_vector(self.index2word[i] + self.seed)
```

**Comment by phanein** [comment]
This is known issue with newer versions of gensim.  I believe your fix should work.  See this issue [for more details](https://github.com/phanein/deepwalk/issues/3).

**Comment by loretoparisi** [comment]
@phanein ah so, thank you for the details! If you like I do a pull req.

**Comment by vsuriya93** [comment]
@phanein 

I have a quick question on the implementation. Why treat the vertices and random walks as integers, when they can be retained as strings? will that make any difference to the representation ?

**Comment by phanein** [comment]
@vsuriya93 Just saw this comment.  For posterity I'll answer.  

The reason this implementation used integers for the random walks was to minimize the memory footprint.  For a while, this was good, but then gensim was patched to assume that it was operating on strings.
