### ISSUE TITLE
'NoneType' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by Viper1-1** [phanein/deepwalk#135]
This error has come up multiple times whenever I try to use the Fluent Wires or Fluent Pipes. 
When I try to run Fluent Wire, I receive this error:
`Python: Traceback (most recent call last):
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power_trip/power_trip_wire.py", line 1084, in modal
self.put curvel)
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power trip/power trip_wire.py", line 885, in put curve
self.make wire()
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power_trip/power_ trip_wire.py", line 750, in make wire
self.load geometry_node()
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power_trip/power_trip_wire.py", line 690, in load geometry_node
nodes = tree.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'`

And when I try to run Fluent Pipes, I receive this error:
`File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power trip/power trip pipe.py", line 1135, in modal
self.put curve()
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power trip/power trip_pipe.py", line 932, in put_ curve
self.make pipe()
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power trip/power trip pipe.py", line 755, in make pipe
self.load geometry_node()
File "/Users/sasansamit/Library/Application Support/Blender/3.3/scripts/addons/fluent/power trip/power_trip_pipe.py", line 609, in load geometry_node
nodes = tree.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'`

Any help is appreciated. Also, this is on Mac.

**Comment by NeenLee** [comment]
I also encountered this problem, have you solved it？
