### ISSUE TITLE
ValueError: Unknown mat file type, version 32, 49

### ISSUE THREAD

**Issue by loretoparisi** [phanein/deepwalk#14]
I'm trying to get the adjacency matrix for matlab format of the example:

```shell
macbookproloreto:deepwalk admin$ deepwalk --format mat --matfile adjlist --input example_graphs/karate.adjlist --output karate.embeddings
```

but I get an error

```
Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 9, in <module>
    load_entry_point('deepwalk==1.0.1', 'console_scripts', 'deepwalk')()
  File "/Library/Python/2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/__main__.py", line 157, in main
    process(args)
  File "/Library/Python/2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/__main__.py", line 52, in process
    G = graph.load_matfile(args.input, variable_name=args.matfile_variable_name, undirected=args.undirected)
  File "/Library/Python/2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/graph.py", line 263, in load_matfile
    mat_varables = loadmat(file_)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/io/matlab/mio.py", line 125, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/io/matlab/mio.py", line 55, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/io/matlab/miobase.py", line 236, in get_matfile_version
    % ret)
ValueError: Unknown mat file type, version 32, 49
```

**Comment by phanein** [comment]
@loretoparisi - I am not sure exactly what you want to do, but here is an example of how to use matlab files as input:

`deepwalk --format mat --matfile-variable-name network  --input example_graphs/blogcatalog.mat --output blogcatalog.embeddings`

**Comment by loretoparisi** [comment]
@phanein got it I will check it out.

**Comment by aswathydiv36** [comment]
Traceback (most recent call last):
  File "__main__.py", line 165, in <module>
    sys.exit(main())
  File "__main__.py", line 162, in main
    process(args)
  File "__main__.py", line 57, in process
    G = graph.load_matfile(args.input, variable_name=args.matfile_variable_name, undirected=args.undirected)
  File "/home/aswathy/.local/lib/python2.7/site-packages/deepwalk/graph.py", line 263, in load_matfile
    mat_varables = loadmat(file_)
  File "/home/aswathy/.local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/aswathy/.local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable


why do i get this error?
