### ISSUE TITLE
为什么我安装有问题呢，显示 from skipgram import Skipgram ImportError: No module named 'skipgram'

### ISSUE THREAD

**Issue by xiongmi** [phanein/deepwalk#29]
E:\实验\全视角特征\deepwalk>deepwalk --input example_graphs/karate.adjlist --output karate.embeddings
C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\gensim\utils.py:840: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\gensim\utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
Traceback (most recent call last):
  File "C:\Users\FIRST\AppData\Local\Programs\Python\Python35\Scripts\deepwalk-script.py", line 9, in <module>
    load_entry_point('deepwalk==1.0.1', 'console_scripts', 'deepwalk')()
  File "C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2229, in load
    return self.resolve()
  File "C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\FIRST\AppData\Local\Programs\Python\Python35\lib\site-packages\deepwalk-1.0.1-py3.5.egg\deepwalk\__main__.py", line 16, in <module>
    from skipgram import Skipgram
ImportError: No module named 'skipgram'

**Comment by xiongmi** [comment]
谢谢 ，我已经解决啦

**Comment by songzenghui** [comment]
我也遇到相同问题了，哥们能说一下怎么解决的吗

**Comment by songzenghui** [comment]
@xiongmi

**Comment by lintseju** [comment]
modify 
from skipgram import Skipgram
to 
from deepwalk.skipgram import Skipgram
in deepwalk/__main__.py
https://stackoverflow.com/questions/40579928/cannot-import-module-after-install
