### ISSUE TITLE
ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead.

### ISSUE THREAD

**Issue by chensian** [phanein/deepwalk#44]
my scikit version is  0.17
 i get the error when i run the score.py

here is the full stacktrace

Traceback (most recent call last):
  File "F:\local_work\deepwalk\example_graphs\scoring.py", line 111, in <module>
    results[average] = f1_score(y_test,  preds, average=average)
  File "D:\Programs\Anaconda2\lib\site-packages\sklearn\metrics\classification.py", line 639, in f1_score
    sample_weight=sample_weight)
  File "D:\Programs\Anaconda2\lib\site-packages\sklearn\metrics\classification.py", line 756, in fbeta_score
    sample_weight=sample_weight)
  File "D:\Programs\Anaconda2\lib\site-packages\sklearn\metrics\classification.py", line 956, in precision_recall_fscore_support
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "D:\Programs\Anaconda2\lib\site-packages\sklearn\metrics\classification.py", line 74, in _check_targets
    type_pred = type_of_target(y_pred)
  File "D:\Programs\Anaconda2\lib\site-packages\sklearn\utils\multiclass.py", line 251, in type_of_target
    raise ValueError('You appear to be using a legacy multi-label data'
ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead.

what does this mean?

I tried

        from sklearn.preprocessing import MultiLabelBinarizer  
        y=MultiLabelBinarizer().fit_transform(y)  

but is doesn't run

**Comment by GTmac** [comment]
Please refer to #32 .

**Comment by chensian** [comment]
Thanks
