### ISSUE TITLE
Deepwalk doesn't run in daemonic processes

### ISSUE THREAD

**Issue by cthoyt** [phanein/deepwalk#68]
We're trying to run deepwalk in a daemonic process (an asynchronous task queue run with celery) and we're getting an error because it's doing some multiprocess magic:

```python-traceback
Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/gene-prioritization/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/gene-prioritization/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/cthoyt/dev/gene-prioritization/src/gene_prioritization/web/wsgi.py", line 96, in my_task
    return do_it(CONFIG_PATH, entrez_gene_ids, ppi_graph)
  File "/Users/cthoyt/dev/gene-prioritization/src/gene_prioritization/web/tasks.py", line 70, in do_it
    result_output=gat2vec_result_output,
  File "/Users/cthoyt/dev/gene-prioritization/src/gene_prioritization/pipeline.py", line 163, in rank_genes_gat2vec
    g2v = Gat2Vec(input_directory, input_directory, label=False, tr=TR)
  File "/Users/cthoyt/.virtualenvs/gene-prioritization/src/gat2vec/src/GAT2VEC/gat2vec.py", line 24, in __init__
    self.Gs = parsers.get_graph(self.dataset_dir)
  File "/Users/cthoyt/.virtualenvs/gene-prioritization/src/gat2vec/src/GAT2VEC/parsers.py", line 13, in get_graph
    G = graph.load_adjacencylist(fname_struct)
  File "/Users/cthoyt/.virtualenvs/gene-prioritization/lib/python3.7/site-packages/deepwalk/graph.py", line 224, in load_adjacencylist
    for idx, adj_chunk in enumerate(executor.map(parse_func, grouper(int(chunksize), f))):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 645, in map
    timeout=timeout)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 575, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 575, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 615, in submit
    self._start_queue_management_thread()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 569, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/process.py", line 593, in _adjust_process_count
    p.start()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 110, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

I would suggest making a change to the following lines to allow this function to either be run in a multiprocessing environment (by default) or a single core environment if needed:

https://github.com/phanein/deepwalk/blob/5d4adc17b6e1afddfcdc7d63a036a6740475f5ca/deepwalk/graph.py#L221-L226

@ozlemmuslu and I would be happy to submit a PR if you think this is a good idea

**Comment by cthoyt** [comment]
Closed by #69 

Thank you @GTmac for the correspondence and looking over our PR. We really appreciate it! Do you think you might be able to make a (v1.0.4?) release to PyPI?

**Comment by GTmac** [comment]
@cthoyt Sorry for my late reply! I personally would like to make a few other changes to DeepWalk before making another release -- this should happen in September when I have more time to work on DeepWalk. Does this sound reasonable?

**Comment by cthoyt** [comment]
Fine with me!

Sorry for the late reply, too. Thanks for sharing your wonderful work!

**Comment by cthoyt** [comment]
Hey @GTmac, is there any news on a new release?
