### ISSUE TITLE
Some questions when I run code

### ISSUE THREAD

**Issue by Shodowelf** [phanein/deepwalk#94]
Hello,sir
When I run you code I meet some questions , can you tell me how to solve it ? 
When I run main.py .My question is as follow:
/home/zhen/HERec-master/venv/bin/python /home/zhen/deep/deepwalk-master/deepwalk/__main__.py
Traceback (most recent call last):
  File "/home/zhen/deep/deepwalk-master/deepwalk/__main__.py", line 13, in <module>
    from . import graph
ValueError: Attempted relative import in non-package
I don't no what package is need.
when I run walks.py .My question is as follow:
Traceback (most recent call last):
  File "/home/zhen/deep/deepwalk-master/deepwalk/walks.py", line 12, in <module>
    from . import graph
ValueError: Attempted relative import in non-package
The same question.
Thank you.

**Comment by Shodowelf** [comment]
After my debug my question change it.
usage: deepwalk [-h] [--debug] [--format FORMAT] --input [INPUT] [-l LOG]
                [--matfile-variable-name MATFILE_VARIABLE_NAME]
                [--max-memory-data-size MAX_MEMORY_DATA_SIZE]
                [--number-walks NUMBER_WALKS] --output OUTPUT
                [--representation-size REPRESENTATION_SIZE] [--seed SEED]
                [--undirected UNDIRECTED] [--vertex-freq-degree]
                [--walk-length WALK_LENGTH] [--window-size WINDOW_SIZE]
                [--workers WORKERS]
deepwalk: error: argument --input is required
what can I do to solve it?

**Comment by GTmac** [comment]
If you take a look at the README, there are some arguments to be specified -- what if you run `deepwalk --input example_graphs/karate.adjlist --output karate.embeddings`?
