### ISSUE TITLE
AttributeError: 'Word2Vec' object has no attribute 'wv'

### ISSUE THREAD

**Issue by YutingSun163** [phanein/deepwalk#97]
When I run __main__.py, an error occured: 
Traceback (most recent call last):
  File "__main__.py", line 168, in <module>
    sys.exit(main())
  File "__main__.py", line 165, in main
    process(args)
  File "__main__.py", line 101, in process
    model.wv.save_word2vec_format(args.output)
AttributeError: 'Word2Vec' object has no attribute 'wv'

My python version is 3.7.0, and gensim version 0.10.2

**Comment by GTmac** [comment]
The gensim version is too old -- please try the latest version of gensim and let me know if that works. Thanks!

**Comment by YutingSun163** [comment]
I tried upgrade the gensim version to the latest, but new error occur: 

> Traceback (most recent call last):
  File "__main__.py", line 17, in <module>
    from gensim.models import Word2Vec
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/gensim-3.8.0-py3.7-macosx-10.9-x86_64.egg/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/gensim-3.8.0-py3.7-macosx-10.9-x86_64.egg/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/gensim-3.8.0-py3.7-macosx-10.9-x86_64.egg/gensim/parsing/preprocessing.py", line 42, in <module>
    from gensim import utils
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/gensim-3.8.0-py3.7-macosx-10.9-x86_64.egg/gensim/utils.py", line 45, in <module>
    from smart_open import open
ImportError: cannot import name 'open' from 'smart_open' (/Users/apple/Library/Python/3.7/lib/python/site-packages/smart_open/__init__.py)

**Comment by YutingSun163** [comment]
And also I got error : file not exist: karate.embeddings, although I have manually created one.

**Comment by GTmac** [comment]
Sorry for the late reply. For posterity, it seems that gensim is not properly installed on your machine.

**Comment by GTmac** [comment]
> And also I got error : file not exist: karate.embeddings, although I have manually created one.

This is the embeddings file produced by DeepWalk on the Karate graph -- it should not be manually created.
